package com.diarcastro.drupalgenerator

fun templateComponent(componentData: ComponentData) : ByteArray {
    val schema = componentData.schema
    val componentTitle = componentData.toTitle()
    val componentStatus = componentData.status;

    return """# Generated by Drupal SDC Generator Plugin
# Diego Castro <ing.diegocastro@gmail.com>

$schema
name: $componentTitle
status: $componentStatus

props:
  type: object
  required:
    - text

  properties:
    text:
      title: Text
      type: string

# slots:
#   body:
#     title: Body
#     required: true
#     description: This is the body
""".toByteArray()
}